baseurl = "https://gocivici.com/blog/"
theme= hugo_theme_robust
languageCode = "en-us"
title = "blog.write(projectLogs)"
author = "Görkem Bozkurt"
copyright = "Copyright (c) 2016, Görkem Bozkurt; all rights reserved."
googleAnalytics = "UA-83687635-2"
[params]
  disqusShortname = "gocivici"
[taxonomies]
  category = "categories"
  tag = ""
